### PR TITLE
Switch to using enginefacade

### PR DESCRIPTION
**Pull request by scrungus**
Closes-Bug: #2067345
Change-Id: If9a2c96628cfcb819fee5e19f872ea015979b30f

Co-authored-by: scrungus <tyler@stackhpc.com>

### CODE REVIEW

**Comment by mnasiadka** [comment]
Can we get that at least upstream CI tested before we build that and deploy anywhere?

**Comment by mnasiadka** [comment]
Oh boy, we don't even run tox tests in that repo.

**Comment by mnasiadka** [comment]
Ah, because the PR is targeted for master...
@scrungus please target that for stackhpc/2024.1 repo.

**Comment by scrungus** [comment]
closing in favour of #176

**Pull request closed without merging**
